version: '3.9'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/code-snippet-docker
    depends_on:
      - mongodb

  client:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - server

volumes:
  mongo-data:
